[versions]
kotlinVersion="2.0.21"
lwJavaVersion="0.4.5"
kotestVersion="5.9.1"
testcontainersVersion="1.20.6"

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.2.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
superPublish = { id = "com.vanniktech.maven.publish", version = "0.31.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.2" }
release = { id = "net.researchgate.release", version = "3.1.0"}

[libraries]
okhttp = { group = "com.squareup.okhttp3", name="okhttp", version="4.12.0"}
gson = { group = "com.google.code.gson", name="gson", version="2.13.0" }
kotlinreflect = { group = "org.jetbrains.kotlin", name="kotlin-reflect", version.ref = "kotlinVersion" }
ktestjunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlinVersion" }
lwjavacore = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-core", version.ref = "lwJavaVersion"}
lwjavarepo = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-repo-client", version.ref = "lwJavaVersion"}
lwjavarepotesting = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-repo-client-testing", version.ref = "lwJavaVersion"}
lwjavaextensions = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-extensions", version.ref = "lwJavaVersion"}
kotestrunner = { module="io.kotest:kotest-runner-junit5-jvm", version.ref = "kotestVersion"}
kotestassertions = { module="io.kotest:kotest-assertions-core", version.ref = "kotestVersion"}
kotestproperty = { module="io.kotest:kotest-property", version.ref = "kotestVersion" }
testcontainers =  { module="org.testcontainers:testcontainers", version.ref = "testcontainersVersion" }
testcontainersjunit = { module="org.testcontainers:junit-jupiter", version.ref = "testcontainersVersion" }
testcontainerspg = { module="org.testcontainers:postgresql", version.ref = "testcontainersVersion" }
protobuf = { module="com.google.protobuf:protobuf-java", version = "4.30.2" }
